name = "scaro-biglietti"
main = "index.js"
compatibility_date = "2024-11-01"

# Crea il namespace con: wrangler kv namespace create TICKETS
# e incolla qui l'id che ti restituisce.
kv_namespaces = [
  { binding = "TICKETS", id = "f062bf9751004816b931847615ebf25a" }
]
